/*
 * Authentication API
 * An authentication API implemented in Node.js
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.26
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AuthenticationApi);
  }
}(this, function(expect, AuthenticationApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AuthenticationApi.UserApi();
  });

  describe('(package)', function() {
    describe('UserApi', function() {
      describe('userDelete', function() {
        it('should call userDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for userDelete call and complete the assertions
          /*
          var password = new AuthenticationApi.UserPassword();
          password.password = "";

          instance.userDelete(password, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(AuthenticationApi.UserData);
            expect(data.email).to.be.a('string');
            expect(data.email).to.be("");
            expect(data.role).to.be.a('string');
            expect(data.role).to.be("");
            expect(data.verified).to.be.a('boolean');
            expect(data.verified).to.be(false);
            expect(data.created).to.be.a(Date);
            expect(data.created).to.be(new Date());
            expect(data.last).to.be.a(Date);
            expect(data.last).to.be(new Date());
            expect(data.fullName).to.be.a('string');
            expect(data.fullName).to.be("");
            expect(data.address).to.be.a('string');
            expect(data.address).to.be("");
            expect(data.city).to.be.a('string');
            expect(data.city).to.be("");
            expect(data.postal).to.be.a('string');
            expect(data.postal).to.be("");
            expect(data.phone).to.be.a('string');
            expect(data.phone).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('userGet', function() {
        it('should call userGet successfully', function(done) {
          // TODO: uncomment userGet call and complete the assertions
          /*

          instance.userGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(AuthenticationApi.UserData);
            expect(data.email).to.be.a('string');
            expect(data.email).to.be("");
            expect(data.role).to.be.a('string');
            expect(data.role).to.be("");
            expect(data.verified).to.be.a('boolean');
            expect(data.verified).to.be(false);
            expect(data.created).to.be.a(Date);
            expect(data.created).to.be(new Date());
            expect(data.last).to.be.a(Date);
            expect(data.last).to.be(new Date());
            expect(data.fullName).to.be.a('string');
            expect(data.fullName).to.be("");
            expect(data.address).to.be.a('string');
            expect(data.address).to.be("");
            expect(data.city).to.be.a('string');
            expect(data.city).to.be("");
            expect(data.postal).to.be.a('string');
            expect(data.postal).to.be("");
            expect(data.phone).to.be.a('string');
            expect(data.phone).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('userPut', function() {
        it('should call userPut successfully', function(done) {
          // TODO: uncomment, update parameter values for userPut call and complete the assertions
          /*
          var user = new AuthenticationApi.UserPut();
          user.fullName = "";
          user.address = "";
          user.city = "";
          user.postal = "";
          user.phone = "";

          instance.userPut(user, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(AuthenticationApi.UserData);
            expect(data.email).to.be.a('string');
            expect(data.email).to.be("");
            expect(data.role).to.be.a('string');
            expect(data.role).to.be("");
            expect(data.verified).to.be.a('boolean');
            expect(data.verified).to.be(false);
            expect(data.created).to.be.a(Date);
            expect(data.created).to.be(new Date());
            expect(data.last).to.be.a(Date);
            expect(data.last).to.be(new Date());
            expect(data.fullName).to.be.a('string');
            expect(data.fullName).to.be("");
            expect(data.address).to.be.a('string');
            expect(data.address).to.be("");
            expect(data.city).to.be.a('string');
            expect(data.city).to.be("");
            expect(data.postal).to.be.a('string');
            expect(data.postal).to.be("");
            expect(data.phone).to.be.a('string');
            expect(data.phone).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
